version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://prueba:prueba@postgres:5432/prueba
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-change-me
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GOOGLE_CLIENT_SECRET=your-google-client-secret
      - APPLE_CLIENT_ID=your-apple-client-id
      - APPLE_CLIENT_SECRET=your-apple-client-secret
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=prueba
      - POSTGRES_PASSWORD=prueba
      - POSTGRES_DB=prueba
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
volumes:
  postgres_data: